# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
        exclude: (docs|tests/wiki|tw-plugin)
    -   id: check-added-large-files
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.910
    hooks:
    -   id: mypy
        files: anki-plugin/src
        additional_dependencies:
            - types-requests==2.25.8
            - pyqt6==6.2.2
            - anki==2.1.50b2
            - aqt==2.1.50b2

-   repo: local
    hooks:
    -   id: pylint
        name: pylint score >= 9.0
        entry: pylint
        language: system
        types: [python]
        args: ["--fail-under=9.0", "anki-plugin/src"]
    - id: pytest-check
      name: pytest-check
      entry: pytest
      language: system
      pass_filenames: false
      args: ["--cov-fail-under=90"]
