# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
        exclude: (docs|tests/wiki|tw-plugin)
    -   id: check-added-large-files
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.782
    hooks:
    -   id: mypy

-   repo: local
    hooks:
    -   id: pylint
        name: pylint score >= 9.0
        entry: pylint
        language: system
        types: [python]
        args: ["--fail-under=9.0", "anki-plugin/src"]
