# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'designer/settings_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(545, 449)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.defaultDeck_ = QtWidgets.QLineEdit(Dialog)
        self.defaultDeck_.setObjectName("defaultDeck_")
        self.gridLayout.addWidget(self.defaultDeck_, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.tiddlywikiBinary_ = QtWidgets.QLineEdit(Dialog)
        self.tiddlywikiBinary_.setObjectName("tiddlywikiBinary_")
        self.gridLayout.addWidget(self.tiddlywikiBinary_, 1, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.label_8 = QtWidgets.QLabel(Dialog)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_2.addWidget(self.label_8)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.deleteWikiButton = QtWidgets.QPushButton(Dialog)
        self.deleteWikiButton.setObjectName("deleteWikiButton")
        self.gridLayout_3.addWidget(self.deleteWikiButton, 1, 1, 1, 1)
        self.addWikiButton = QtWidgets.QPushButton(Dialog)
        self.addWikiButton.setObjectName("addWikiButton")
        self.gridLayout_3.addWidget(self.addWikiButton, 0, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem, 2, 1, 1, 1)
        self.wikiList = QtWidgets.QListWidget(Dialog)
        self.wikiList.setObjectName("wikiList")
        self.gridLayout_3.addWidget(self.wikiList, 0, 0, 3, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_3)
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 0, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 1, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 2, 0, 1, 1)
        self.path_ = QtWidgets.QLineEdit(self.groupBox)
        self.path_.setObjectName("path_")
        self.gridLayout_2.addWidget(self.path_, 2, 1, 1, 1)
        self.browseButton = QtWidgets.QPushButton(self.groupBox)
        self.browseButton.setObjectName("browseButton")
        self.gridLayout_2.addWidget(self.browseButton, 2, 2, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 3, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 4, 0, 1, 1)
        self.type_ = QtWidgets.QComboBox(self.groupBox)
        self.type_.setObjectName("type_")
        self.type_.addItem("")
        self.type_.addItem("")
        self.type_.addItem("")
        self.gridLayout_2.addWidget(self.type_, 1, 1, 1, 2)
        self.wikiName = QtWidgets.QLineEdit(self.groupBox)
        self.wikiName.setObjectName("wikiName")
        self.gridLayout_2.addWidget(self.wikiName, 0, 1, 1, 2)
        self.contentFilter_ = QtWidgets.QLineEdit(self.groupBox)
        self.contentFilter_.setObjectName("contentFilter_")
        self.gridLayout_2.addWidget(self.contentFilter_, 3, 1, 1, 2)
        self.permalink_ = QtWidgets.QLineEdit(self.groupBox)
        self.permalink_.setObjectName("permalink_")
        self.gridLayout_2.addWidget(self.permalink_, 4, 1, 1, 2)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.helpButton = QtWidgets.QPushButton(Dialog)
        self.helpButton.setObjectName("helpButton")
        self.horizontalLayout.addWidget(self.helpButton)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.okButton = QtWidgets.QPushButton(Dialog)
        self.okButton.setObjectName("okButton")
        self.horizontalLayout.addWidget(self.okButton)
        self.cancelButton = QtWidgets.QPushButton(Dialog)
        self.cancelButton.setObjectName("cancelButton")
        self.horizontalLayout.addWidget(self.cancelButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.label.setBuddy(self.defaultDeck_)
        self.label_2.setBuddy(self.tiddlywikiBinary_)
        self.label_8.setBuddy(self.wikiList)
        self.label_3.setBuddy(self.wikiName)
        self.label_4.setBuddy(self.type_)
        self.label_5.setBuddy(self.path_)
        self.label_6.setBuddy(self.contentFilter_)
        self.label_7.setBuddy(self.permalink_)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.defaultDeck_, self.tiddlywikiBinary_)
        Dialog.setTabOrder(self.tiddlywikiBinary_, self.wikiList)
        Dialog.setTabOrder(self.wikiList, self.addWikiButton)
        Dialog.setTabOrder(self.addWikiButton, self.deleteWikiButton)
        Dialog.setTabOrder(self.deleteWikiButton, self.wikiName)
        Dialog.setTabOrder(self.wikiName, self.type_)
        Dialog.setTabOrder(self.type_, self.path_)
        Dialog.setTabOrder(self.path_, self.browseButton)
        Dialog.setTabOrder(self.browseButton, self.contentFilter_)
        Dialog.setTabOrder(self.contentFilter_, self.permalink_)
        Dialog.setTabOrder(self.permalink_, self.okButton)
        Dialog.setTabOrder(self.okButton, self.cancelButton)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "TiddlyRemember Configuration"))
        self.label.setText(_translate("Dialog", "Default &Deck"))
        self.label_2.setText(_translate("Dialog", "Path to TiddlyWiki e&xecutable"))
        self.label_8.setText(_translate("Dialog", "&Wikis"))
        self.deleteWikiButton.setText(_translate("Dialog", "De&lete"))
        self.addWikiButton.setText(_translate("Dialog", "&Add"))
        self.groupBox.setTitle(_translate("Dialog", "Wiki settings"))
        self.label_3.setText(_translate("Dialog", "&Name"))
        self.label_4.setText(_translate("Dialog", "&Type"))
        self.label_5.setText(_translate("Dialog", "&Path"))
        self.browseButton.setText(_translate("Dialog", " &Browse..."))
        self.label_6.setText(_translate("Dialog", "&Filter"))
        self.label_7.setText(_translate("Dialog", "Permalin&k"))
        self.type_.setItemText(0, _translate("Dialog", "File"))
        self.type_.setItemText(1, _translate("Dialog", "Folder"))
        self.type_.setItemText(2, _translate("Dialog", "URL"))
        self.helpButton.setText(_translate("Dialog", "&Help"))
        self.okButton.setText(_translate("Dialog", "&OK"))
        self.cancelButton.setText(_translate("Dialog", "&Cancel"))

